
replicaCount: 1

image:
  repository: 0914818516/zuul
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: NodePort
  port: 9999
  targetport: 9999
  nodeport: 32470
  name: zuul-api-gateway

container:
  name: zuul-api-gateway

