
replicaCount: 1

image:
  repository: 0914818516/zuul
  pullPolicy: Always

service:
  type: NodePort
  port: 9999
  name: zuul-api-gateway
  targetport: 9999
  nodeport: 32470

container:
  name: zuul-api-gateway

cpa:
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - react-ui
      topologyKey: "kubernetes.io/nodegroup-name"